### ISSUE TITLE
Github Pages e deixar público

### ISSUE THREAD

**Issue by Ewerton-Jose** [TryAge/Trilhame#6]
Papis, coloca ele no github pages e público, e tbm tenta passar ele para a organização da _TryAge_

**Comment by CarlosfcPinheiro** [comment]
Vou mudar aqui, papis. Só não sei colocar para a organização.

**Comment by Ewerton-Jose** [comment]
Tu faz o seguinte

**1 - Tu vai no settings do projeto**

**2 - Vai  descendo até a _`Danger zone`_**

**3 - Tu aperta em _`Transfer ownership`_**

**Comment by CarlosfcPinheiro** [comment]
Pronto, fiz todas as alterações
